# Generated by Django 4.0.4 on 2022-05-29 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_account_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя карты')),
                ('card_number', models.CharField(max_length=16, verbose_name='Номер карты')),
                ('card_code', models.IntegerField(verbose_name='Код карты')),
                ('card_release', models.DateField(verbose_name='Выпуск карты')),
                ('card_ending', models.DateField(verbose_name='Срок карты')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Баланс')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='cards',
            field=models.ManyToManyField(to='main.cards', verbose_name='Карты'),
        ),
    ]
